"use client";
import {useState} from "react";
const money=n=>"৳"+Number(n||0).toLocaleString("en-BD");
const ORDER_STATUSES=["PENDING","CONFIRMED","PROCESSING","SHIPPED","DELIVERED","CANCELLED"];
const PAYMENT_STATUSES=["UNPAID","PENDING","PAID","FAILED","REFUNDED"];
const SERVICE_STATUSES=["NEW","CONTACTED","SCHEDULED","COMPLETED","CANCELLED"];
export default function AdminDashboard({initial}){
  const [orders,setOrders]=useState(initial.orders),[products,setProducts]=useState(initial.products),[requests,setRequests]=useState(initial.requests),[coupons,setCoupons]=useState(initial.coupons),[msg,setMsg]=useState("");
  async function patchOrder(id,body){setMsg("");const r=await fetch(`/api/admin/orders/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setMsg(d.error||"Order update failed.");return}setOrders(x=>x.map(o=>o.id===id?d.order:o));setMsg("Order updated.")}
  async function patchProduct(id,form){setMsg("");const body=Object.fromEntries(new FormData(form).entries());body.featured=form.featured.checked;body.active=form.active.checked;const r=await fetch(`/api/admin/products/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setMsg(d.error||"Product update failed.");return}setProducts(x=>x.map(p=>p.id===id?d.product:p));setMsg("Product updated.")}
  async function createProduct(e){e.preventDefault();setMsg("");const body=Object.fromEntries(new FormData(e.currentTarget).entries());body.featured=e.currentTarget.featured.checked;body.active=e.currentTarget.active.checked;const r=await fetch("/api/admin/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setMsg(d.error||"Product creation failed.");return}setProducts(x=>[d.product,...x]);e.currentTarget.reset();setMsg("Product created.")}
  async function patchService(id,status){const r=await fetch(`/api/admin/service-requests/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});const d=await r.json();if(!r.ok){setMsg(d.error||"Service update failed.");return}setRequests(x=>x.map(v=>v.id===id?d.request:v));setMsg("Service request updated.")}
  async function createCoupon(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch("/api/admin/coupons",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setMsg(d.error||"Coupon creation failed.");return}setCoupons(x=>[d.coupon,...x]);e.currentTarget.reset();setMsg("Coupon created.")}
  async function toggleCoupon(c){const r=await fetch(`/api/admin/coupons/${c.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:!c.active})});const d=await r.json();if(!r.ok){setMsg(d.error||"Coupon update failed.");return}setCoupons(x=>x.map(v=>v.id===c.id?d.coupon:v));setMsg("Coupon updated.")}
  return <main className="shell section adminPage"><div className="splitHeading"><div><span className="eyebrow">ADMIN OPERATIONS</span><h1>Store control center</h1></div><p>Manage inventory, orders, payment verification, service requests and coupons. Changes are audit logged.</p></div><p className="formMsg stickyMsg" role="status">{msg}</p>
    <div className="statGrid"><div><span>Products</span><b>{products.length}</b></div><div><span>Orders</span><b>{initial.counts.orders}</b></div><div><span>Users</span><b>{initial.counts.users}</b></div><div><span>Service requests</span><b>{initial.counts.requests}</b></div></div>
    <section className="adminSection"><div className="sectionTitle"><div><span className="eyebrow">ORDERS</span><h2>Recent orders</h2></div></div><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Order status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>{o.orderNo}</b><small>{new Date(o.createdAt).toLocaleString("en-BD")}</small></td><td>{o.user?.name}<small>{o.user?.email}<br/>{o.phone}</small></td><td><b>{money(o.total)}</b><small>{o.paymentMethod}{o.paymentTransactionId?<><br/>Ref: {o.paymentTransactionId}</>:null}</small></td><td><select value={o.paymentStatus} onChange={e=>patchOrder(o.id,{paymentStatus:e.target.value})}>{PAYMENT_STATUSES.map(v=><option key={v}>{v}</option>)}</select></td><td><select value={o.status} disabled={o.status==="CANCELLED"} onChange={e=>patchOrder(o.id,{status:e.target.value})}>{ORDER_STATUSES.map(v=><option key={v}>{v}</option>)}</select></td></tr>)}</tbody></table></div></section>
    <section className="adminSection"><div className="sectionTitle"><div><span className="eyebrow">INVENTORY</span><h2>Products</h2></div></div><div className="adminProductGrid">{products.map(p=><form className="productEditCard" key={p.id} onSubmit={e=>{e.preventDefault();patchProduct(p.id,e.currentTarget)}}><div className="productEditHead"><b>{p.name}</b><small>{p.sku} · {p.category.name}</small></div><input name="name" defaultValue={p.name}/><input name="brand" defaultValue={p.brand||""} placeholder="Brand"/><input name="imageUrl" defaultValue={p.imageUrl||""} placeholder="Image URL"/><textarea name="description" rows="3" defaultValue={p.description}/><div className="threeCol"><label>Price<input name="price" type="number" min="0" defaultValue={p.price}/></label><label>Stock<input name="stock" type="number" min="0" defaultValue={p.stock}/></label><label>Low stock<input name="lowStockThreshold" type="number" min="0" defaultValue={p.lowStockThreshold}/></label></div><input name="warranty" defaultValue={p.warranty||""} placeholder="Warranty"/><div className="checkRow"><label><input name="active" type="checkbox" defaultChecked={p.active}/> Active</label><label><input name="featured" type="checkbox" defaultChecked={p.featured}/> Featured</label></div><button className="darkBtn">Save product</button></form>)}</div>
      <details className="adminCreate"><summary>Add new product</summary><form className="formCard" onSubmit={createProduct}><div className="twoCol"><input required name="name" placeholder="Product name"/><input required name="sku" placeholder="SKU"/></div><div className="twoCol"><input required name="slug" placeholder="slug-like-this"/><select required name="categoryId" defaultValue=""><option value="" disabled>Category</option>{initial.categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><textarea required name="description" rows="3" placeholder="Description"/><div className="threeCol"><input required name="price" type="number" min="0" placeholder="Price (BDT)"/><input required name="stock" type="number" min="0" placeholder="Stock"/><input name="brand" placeholder="Brand"/></div><input name="imageUrl" placeholder="https://... image URL"/><input name="warranty" placeholder="Warranty terms"/><div className="checkRow"><label><input name="active" type="checkbox" defaultChecked/> Active</label><label><input name="featured" type="checkbox"/> Featured</label></div><button className="primaryBtn">Create product</button></form></details>
    </section>
    <section className="adminSection"><span className="eyebrow">SERVICE</span><h2>Installation requests</h2><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Customer</th><th>Project</th><th>Location / Date</th><th>Status</th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td><b>{r.name}</b><small>{r.phone}</small></td><td>{r.projectType}<small>{r.notes||"No notes"}</small></td><td>{r.location||"—"}<small>{r.preferredAt?new Date(r.preferredAt).toLocaleDateString("en-BD"):"No preferred date"}</small></td><td><select value={r.status} onChange={e=>patchService(r.id,e.target.value)}>{SERVICE_STATUSES.map(v=><option key={v}>{v}</option>)}</select></td></tr>)}</tbody></table></div></section>
    <section className="adminSection"><span className="eyebrow">PROMOTIONS</span><h2>Coupons</h2><form className="couponForm" onSubmit={createCoupon}><input required name="code" placeholder="CODE"/><input name="percentOff" type="number" min="1" max="100" placeholder="% off"/><input name="flatOff" type="number" min="1" placeholder="Flat BDT off"/><input name="minOrder" type="number" min="0" placeholder="Minimum order"/><button className="primaryBtn">Create</button></form><div className="couponList">{coupons.map(c=><div key={c.id}><div><b>{c.code}</b><small>{c.percentOff?`${c.percentOff}% off`:`${money(c.flatOff)} off`} · min {money(c.minOrder||0)}</small></div><button className="secondaryBtn" onClick={()=>toggleCoupon(c)}>{c.active?"Disable":"Enable"}</button></div>)}</div></section>
  </main>
}
