"use client";
import { useEffect,useMemo,useState } from "react";
const money=n=>"৳"+Number(n||0).toLocaleString("en-BD");
export default function CheckoutClient(){
  const [products,setProducts]=useState([]),[cart,setCart]=useState({}),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[config,setConfig]=useState({payments:{},shippingFee:150,freeShippingMin:50000}),[method,setMethod]=useState("CASH_ON_DELIVERY"),[placed,setPlaced]=useState(null);
  useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem("shbd_cart")||"{}"))}catch{setCart({})}Promise.all([fetch("/api/products").then(r=>r.json()),fetch("/api/public-config").then(r=>r.json())]).then(([p,c])=>{setProducts(p.products||[]);setConfig(c)}).catch(()=>{})},[]);
  const items=useMemo(()=>Object.entries(cart).map(([id,quantity])=>({product:products.find(p=>p.id===id),quantity:Number(quantity)})).filter(x=>x.product&&x.quantity>0),[cart,products]);
  const subtotal=items.reduce((s,x)=>s+x.product.price*x.quantity,0);const shipping=subtotal&&subtotal<Number(config.freeShippingMin||0)?Number(config.shippingFee||0):0;
  function qty(id,d){const n={...cart,[id]:(Number(cart[id])||0)+d};const p=products.find(x=>x.id===id);if(p)n[id]=Math.min(p.stock,n[id]);if(n[id]<=0)delete n[id];setCart(n);localStorage.setItem("shbd_cart",JSON.stringify(n));window.dispatchEvent(new Event("shbd-cart"))}
  async function submit(e){e.preventDefault();setBusy(true);setMsg("");try{const form=Object.fromEntries(new FormData(e.currentTarget).entries());const payload={...form,paymentMethod:method,items:items.map(({product,quantity})=>({productId:product.id,quantity:Number(quantity)}))};const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(r.ok){localStorage.removeItem("shbd_cart");window.dispatchEvent(new Event("shbd-cart"));setCart({});setPlaced(d.order);setMsg(`Order ${d.order.orderNo} created successfully.`)}else setMsg(d.error||"Could not place order.")}catch{setMsg("Network error. Please try again.")}finally{setBusy(false)}}
  const manual=method!=="CASH_ON_DELIVERY";const destination=method==="BKASH"?config.payments?.bkash:method==="NAGAD"?config.payments?.nagad:method==="BANK_TRANSFER"?config.payments?.bank:"";
  if(placed)return <main className="shell section"><div className="successCard"><span className="successIcon">✓</span><span className="eyebrow">ORDER RECEIVED</span><h1>Thank you.</h1><p>Your order <b>{placed.orderNo}</b> has been created.</p><div className="summaryRows"><div><span>Total</span><b>{money(placed.total)}</b></div><div><span>Order status</span><b>{placed.status}</b></div><div><span>Payment status</span><b>{placed.paymentStatus}</b></div></div>{placed.paymentStatus==="PENDING"&&<p className="note">Your manual payment reference was submitted and must be verified by an administrator before it is marked paid.</p>}<a className="primaryBtn" href="/account">View my orders</a></div></main>;
  return <main className="shell section"><div className="splitHeading"><div><span className="eyebrow">SECURE CHECKOUT</span><h1>Review and place your order</h1></div><p>Prices, coupon eligibility and stock are verified again on the server before your order is created.</p></div><div className="checkoutGrid">
    <div className="cartPanel"><h2>Your cart</h2>{items.length?items.map(({product:p,quantity})=><div className="cartItem" key={p.id}><div><b>{p.name}</b><small>{money(p.price)} each</small></div><div className="qty"><button type="button" onClick={()=>qty(p.id,-1)}>−</button><span>{quantity}</span><button type="button" onClick={()=>qty(p.id,1)}>+</button></div></div>):<p className="muted">Your cart is empty. <a href="/shop">Continue shopping →</a></p>}<div className="summaryRows"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Estimated delivery</span><b>{subtotal?shipping===0?"Free":money(shipping):money(0)}</b></div><div className="total"><span>Estimated total</span><b>{money(subtotal+shipping)}</b></div></div></div>
    <form className="formCard" onSubmit={submit}><h2>Delivery details</h2><input required maxLength="100" autoComplete="name" name="recipient" placeholder="Recipient name"/><input required maxLength="30" autoComplete="tel" name="phone" placeholder="Phone number"/><input required maxLength="250" autoComplete="street-address" name="addressLine" placeholder="Street / village / house"/><div className="twoCol"><input maxLength="100" name="area" placeholder="Area / upazila"/><input required maxLength="100" name="district" placeholder="District"/></div><input maxLength="20" autoComplete="postal-code" name="postcode" placeholder="Postcode (optional)"/><textarea maxLength="1000" name="notes" rows="3" placeholder="Order notes (optional)"/><input maxLength="40" name="couponCode" placeholder="Coupon code (optional)"/><small className="muted">Coupon value is verified when the order is submitted.</small><h3>Payment method</h3><label className="radio"><input type="radio" name="payment" checked={method==="CASH_ON_DELIVERY"} onChange={()=>setMethod("CASH_ON_DELIVERY")}/> Cash on delivery</label>{config.payments?.bkash&&<label className="radio"><input type="radio" name="payment" checked={method==="BKASH"} onChange={()=>setMethod("BKASH")}/> bKash manual payment</label>}{config.payments?.nagad&&<label className="radio"><input type="radio" name="payment" checked={method==="NAGAD"} onChange={()=>setMethod("NAGAD")}/> Nagad manual payment</label>}{config.payments?.bank&&<label className="radio"><input type="radio" name="payment" checked={method==="BANK_TRANSFER"} onChange={()=>setMethod("BANK_TRANSFER")}/> Bank transfer</label>}{manual&&<div className="paymentBox"><b>Pay to</b><p>{destination}</p><input required name="paymentSenderAccount" maxLength="60" placeholder="Sender account / phone"/><input required name="paymentTransactionId" maxLength="100" placeholder="Transaction / reference ID"/><small>Payment will remain pending until manually verified.</small></div>}<button className="primaryBtn full" disabled={busy||!items.length}>{busy?"Placing order…":"Place order"}</button><p className="formMsg" role="status">{msg}</p></form>
  </div></main>
}
