"use client";
import { useEffect,useState } from "react";
const money=n=>"৳"+Number(n).toLocaleString("en-BD");
export default function CheckoutClient(){
  const [products,setProducts]=useState([]),[cart,setCart]=useState({}),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{setCart(JSON.parse(localStorage.getItem("shbd_cart")||"{}"));fetch("/api/products").then(r=>r.json()).then(d=>setProducts(d.products||[]))},[]);
  const items=Object.entries(cart).map(([id,quantity])=>({product:products.find(p=>p.id===id),quantity})).filter(x=>x.product);
  const estimate=items.reduce((s,x)=>s+x.product.price*x.quantity,0);
  function qty(id,d){const n={...cart,[id]:(cart[id]||0)+d};if(n[id]<=0)delete n[id];setCart(n);localStorage.setItem("shbd_cart",JSON.stringify(n));window.dispatchEvent(new Event("shbd-cart"))}
  async function submit(e){e.preventDefault();setBusy(true);setMsg("");const form=Object.fromEntries(new FormData(e.currentTarget).entries());const payload={...form,items:Object.entries(cart).map(([productId,quantity])=>({productId,quantity:Number(quantity)}))};const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(r.ok){localStorage.removeItem("shbd_cart");window.dispatchEvent(new Event("shbd-cart"));setCart({});setMsg(`Order ${d.order.orderNo} created successfully.`)}else setMsg(d.error||"Could not place order.");setBusy(false)}
  return <main className="shell section"><div className="splitHeading"><div><span className="eyebrow">SECURE CHECKOUT</span><h1>Review and place your order</h1></div><p>Server-side checkout re-validates price and stock. Sign in before ordering.</p></div><div className="checkoutGrid">
    <div className="cartPanel"><h2>Your cart</h2>{items.length?items.map(({product:p,quantity})=><div className="cartItem" key={p.id}><div><b>{p.name}</b><small>{money(p.price)} each</small></div><div className="qty"><button onClick={()=>qty(p.id,-1)}>−</button><span>{quantity}</span><button onClick={()=>qty(p.id,1)}>+</button></div></div>):<p className="muted">Your cart is empty.</p>}<div className="total"><span>Estimated subtotal</span><b>{money(estimate)}</b></div></div>
    <form className="formCard" onSubmit={submit}><h2>Delivery details</h2><input required name="recipient" placeholder="Recipient name"/><input required name="phone" placeholder="Phone number"/><input required name="addressLine" placeholder="Street / village / house"/><div className="twoCol"><input name="area" placeholder="Area / upazila"/><input required name="district" placeholder="District"/></div><input name="postcode" placeholder="Postcode (optional)"/><textarea name="notes" rows="3" placeholder="Order notes (optional)"/><h3>Payment method</h3><label className="radio"><input type="radio" name="paymentMethod" value="CASH_ON_DELIVERY" defaultChecked/> Cash on delivery</label><label className="radio"><input type="radio" name="paymentMethod" value="ONLINE"/> Online payment (adapter scaffold)</label><button className="primaryBtn full" disabled={busy||!items.length}>{busy?"Placing order…":"Place order"}</button><p className="formMsg">{msg}</p></form>
  </div></main>
}
