"use client";
import { useEffect,useMemo,useState } from "react";
const money=n=>"৳"+Number(n).toLocaleString("en-BD");
function addToCart(p){const c=JSON.parse(localStorage.getItem("shbd_cart")||"{}");c[p.id]=Math.min(p.stock,(Number(c[p.id])||0)+1);localStorage.setItem("shbd_cart",JSON.stringify(c));window.dispatchEvent(new Event("shbd-cart"))}
export default function ShopClient(){
  const [products,setProducts]=useState([]),[loading,setLoading]=useState(true),[q,setQ]=useState(""),[category,setCategory]=useState("all"),[sort,setSort]=useState("featured"),[wishlist,setWishlist]=useState(new Set()),[toast,setToast]=useState("");
  useEffect(()=>{const u=new URL(window.location.href),c=u.searchParams.get("category");if(c)setCategory(c);Promise.all([fetch("/api/products").then(r=>r.json()),fetch("/api/wishlist").then(r=>r.json())]).then(([p,w])=>{setProducts(p.products||[]);setWishlist(new Set(w.items||[]));setLoading(false)}).catch(()=>setLoading(false))},[]);
  const categories=[...new Set(products.map(p=>p.category.name))];
  const filtered=useMemo(()=>{let x=products.filter(p=>(category==="all"||p.category.name===category)&&(!q||`${p.name} ${p.brand||""} ${p.description} ${p.category.name}`.toLowerCase().includes(q.toLowerCase())));if(sort==="priceAsc")x=[...x].sort((a,b)=>a.price-b.price);if(sort==="priceDesc")x=[...x].sort((a,b)=>b.price-a.price);if(sort==="newest")x=[...x].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));return x},[products,q,category,sort]);
  async function toggleWish(id){const active=wishlist.has(id);const r=await fetch("/api/wishlist",{method:active?"DELETE":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:id})});const d=await r.json();if(!r.ok){setToast(d.error||"Could not update wishlist.");return}const next=new Set(wishlist);active?next.delete(id):next.add(id);setWishlist(next);setToast(active?"Removed from wishlist.":"Saved to wishlist.")}
  return <main className="shell section"><div className="splitHeading"><div><span className="eyebrow">PRODUCT CATALOG</span><h1>Shop solar equipment</h1></div><p>Live stock, account-based ordering and server-verified checkout for Bangladesh.</p></div>
    <div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search panels, inverter, battery..." aria-label="Search products"/><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Category"><option value="all">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort"><option value="featured">Featured</option><option value="newest">Newest</option><option value="priceAsc">Price: low to high</option><option value="priceDesc">Price: high to low</option></select></div>
    <div className="catalogMeta"><p className="muted">{loading?"Loading inventory…":`${filtered.length} products`}</p><p className="formMsg" role="status">{toast}</p></div>
    <div className="productGrid">{filtered.map(p=><article className="productCard" key={p.id}><div className="productMedia">{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>:<span>{p.category.name==="Solar Panels"?"▦":p.category.name==="Inverters"?"⌁":p.category.name==="Batteries"?"▣":p.category.name==="Solar Kits"?"⌂":"☼"}</span>}{p.featured&&<b>Featured</b>}<button className={`wishBtn ${wishlist.has(p.id)?"saved":""}`} aria-label="Toggle wishlist" onClick={()=>toggleWish(p.id)}>{wishlist.has(p.id)?"♥":"♡"}</button></div><div className="productBody"><small>{p.category.name}</small><h3><a href={`/product/${p.slug}`}>{p.name}</a></h3>{p.brand&&<div className="brandLine">{p.brand}</div>}<p>{Array.isArray(p.specs)?p.specs.slice(0,2).join(" · "):""}</p><div className="priceRow"><strong>{money(p.price)}</strong><span className={p.stock>0?"inStock":"outStock"}>{p.stock>0?`${p.stock} in stock`:"Out of stock"}</span></div><div className="cardActions"><a className="secondaryBtn" href={`/product/${p.slug}`}>Details</a><button className="darkBtn" disabled={p.stock<1} onClick={()=>{addToCart(p);setToast(`${p.name} added to cart.`)}}>Add to cart</button></div></div></article>)}</div>
  </main>
}
